name: CI Pipeline for Verdant Sphere Landing Page

on:
  pull_request:
    branches:
      - dev
      - main
  push:
    branches:
      - dev
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Dependencies
        uses: ./.github/workflows/dependencies-handler

      - name: Run build command
        run: npm run test
          
  build:
    name: Build Code
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Setup Dependencies
        uses: ./.github/workflows/dependencies-handler

      - name: Run build command
        run: npm run build

  